/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xx.h"

void delay()
{
	for(uint32_t i = 0; i < 300000/2; i++);
}

int main()
{
	GPIO_Handle_t GPIO_Led, GPIO_Btn;

	GPIO_Led.pGPIOx = GPIOC;
	GPIO_Led.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GPIO_Led.GPIO_PinConfig.GPIO_PinType = GPIO_MODE_OUT_HIGH_SPEED;
	GPIO_Led.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT_PP;

	GPIO Led(GPIO_Led);

	Led.GPIO_Init();

	GPIO_Btn.pGPIOx = GPIOB;
	GPIO_Btn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_4;
	GPIO_Btn.GPIO_PinConfig.GPIO_PinType = GPIO_MODE_IN;
	GPIO_Btn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN_FLOAT;

	GPIO Btn(GPIO_Btn);

	Btn.GPIO_Init();

	while(1)
	{
		if (Btn.GPIO_ReadFromInputPin() == RESET)
		{
			delay();
			while(Btn.GPIO_ReadFromInputPin() == RESET);
			Led.GPIO_ToggleOutputPin();
		}
	}

	return 0;
}



